### PR TITLE
A little cleanup.

### PR DESCRIPTION
**Pull request by koteelok**
For some reason your library was looking more like a project template. I removed unnecessary directories and files (assets, heaps), the presence of which could break the compilation, slightly rewrote haxelib.json and removed the contents of include.xml, but left the file for future changes.

The library now looks more like a... _library_.

### CODE REVIEW

**Comment by ShaharMS** [comment]
Before each release i remove those files. The reason they exist is for testing the library within itself cause i found it to be the fastest. I can understand removing the heaps thing and the assets directory (which i forgot about lol) but I'm afraid that removing project.xml will disable autocomplete on this project(?)

I will however remove main.hx and project.xml before releases

**Comment by koteelok** [comment]
If you need them so much for the test, why not just add them to .gitignore?

**Comment by koteelok** [comment]
Many people clone libraries directly from github, but this structure within the repository makes it impossible.

**Comment by ShaharMS** [comment]
I wanted to keep things un-gitignored at the start because i worked from multiple PCs and I needed to update the configuration if the tests each time. Altho, now I don't really need that because the tests exist on both PCs. I think I'll merge this PR and just gitignore Main.hx and project.xml instead of deleting them (will probably do that later today tho, I'm working on some more stuff for the library)

**Comment by ShaharMS** [comment]
Ok, im going to merge this PR, but instead of completely deleting project.xml and Main.hx ill gitignore them

**Comment by koteelok** [comment]
Bro, if you need some useless for others, but needed for you stuff, just create new branch.

**Pull request merged**
