### PR TITLE
Simplified and formatted

### PR DESCRIPTION
**Pull request by Wither362**
Simplified and formatted, I tested it and it works perfectly

### CODE REVIEW

**Comment by ShaharMS** [comment]
just before i merge, i wanna know some things:

 - Are those only formatting changes?
  - are there any changes to logical stuff, or only unnecessary syntax removal/replacement?

**Comment by Wither362** [comment]
> just before i merge, i wanna know some things:
> 
> * Are those only formatting changes?
> * are there any changes to logical stuff, or only unnecessary syntax removal/replacement?

This only are:
- file formats 
- simplified

don’t worry I tested it

**Comment by ShaharMS** [comment]
nice, is this ready to merge?

**Comment by Wither362** [comment]
> nice, is this ready to merge?

Ye

**Comment by Wither362** [comment]
But merge and squash it

**Pull request merged**
